apiVersion: apps/v1
kind: Deployment
metadata:
  name: testphp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testphp
  template:
    metadata:
      labels:
        app: testphp
    spec:
      containers:
        - name: apache
          image: testphp:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
