apiVersion: apps/v1
kind: Deployment
metadata:
  name: brilliantapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brilliantapp
  template:
    metadata:
      labels:
        app: brilliantapp
    spec:
      containers:
        - name: apache
          image: brilliantapp:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
